# Generated by Django 5.1.7 on 2025-03-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobapplication",
            old_name="comaapny_name",
            new_name="company_name",
        ),
    ]
