# Generated by Django 5.1.7 on 2025-03-22 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_rename_comaapny_name_jobapplication_company_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobapplication",
            old_name="apllication_date",
            new_name="application_date",
        ),
    ]
